site_name: Coredump
docs_dir: notes
site_dir: site

site_name: Coredump

docs_dir: notes

repo_url: https://github.com/ioztelcan/coredump
repo_name: Github

site_author: "ioztelcan"

#theme: readthedocs
#theme_dir: readthedocs_custom

#markdown_extensions:
#  - smarty
#  - footnotes
#  - toc:
#      permalink: True

pages:
  - Home: index.md

  - 'Cheatsheets': 'notes/cheatsheets/*'  
